### ISSUE TITLE
drivers_fpga: allow switching between different bitstreams

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/genode-zynq#2]
The `pkg/drivers_fpga-zynq` takes care of loading a single bitstream into the FPGA and changing the devices ROM of the platform driver accordingly. However, as soon as we want to switch between different bitstreams, the `drivers_fpga-zynq` subsystem is of no use any more.

We can modify the subsystem as follows in order to allow switching between different bitstreams:

- Instead of providing a `fpga_devices` ROM, we provide a ROM with the following structure in order to specify what devices are enabled by which bitstream:
```
<config>
  <bitstream name="...">
     <devices>
       [...]
     </devices>
  </bitstream>
</config>
```
- We replace the `fpga.bit` ROM by a File system session that provides the bitstream files. This file system is mounted into the VFS of the `fpga_drv`.
- Instead of reading the path of the bitstream to be loaded from the config ROM, the `fpga_drv` will read a `/config` file from its VFS.

**Comment by nfeske** [comment]
I'm wondering if the dependency of the fpga driver from the (rather complex) VFS infrastructure could not be avoided? What would speak against supplying the bitstream as a (dynamic) ROM? For the convenient management of bitstreams as files, one could use an fs_rom, like Sculpt does for the config fs.

**Comment by jschlatow** [comment]
@nfeske Thanks for your feedback!

Reducing complexity is a good point. If I remember correctly, the motivation behind using the VFS for bitstream access was that I needed an exact size. There are two formats supported: a raw version and a version with header (and swapped bytes). The raw version does not have a size information since there is no header, hence I depend on the file size. I was not sure whether the ROM dataspace size exactly reflects the file size. I believe in case of fs_rom it does, hence it'd be worth a try.

**Comment by nfeske** [comment]
> the motivation behind using the VFS for bitstream access was that I needed an exact size.

That explains it. The size of ROM modules can only be a multiple of 4 KiB (page size) because a ROM is served as a bunch of memory pages. So if the exact byte size of the data is needed, we are out of luck.

**Comment by jschlatow** [comment]
Yet, if include the bitstream as a rom file system into the VFS, I get the exact byte size. Is this a special case when the rom is served by core?

**Comment by nfeske** [comment]
Hehe... that's a special case _you_ introduced in https://github.com/genodelabs/genode/issues/2903 ;-)

**Comment by jschlatow** [comment]
That is true, yet I'm not even using this feature. Apparently, the configuration interface allows transferring additional bytes as long as they don't accidentally contain any valid bitstream instructions.

Given that the default bitstream format is that one _with_ header information and given that the size of the bitstream is a device constant, I'm considering adding an optional size attribute to the fpga driver's config. With this, we could actually remove the VFS dependency from the driver since the bitstream size is either specified by the file header or by the driver's config.
